name: roxcard
description: Современное приложение для эмуляции банковских карт через NFC
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Базовые иконки
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  material_design_icons_flutter: ^7.0.7296
  
  # Работа с NFC
  nfc_manager: ^3.3.0
  
  # Управление состоянием
  provider: ^6.0.5
  
  # Хранение данных
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  
  # UI компоненты
  flutter_animate: ^4.2.0
  google_fonts: ^5.1.0
  flutter_slidable: ^3.0.0
  shimmer: ^3.0.0
  
  # Сканирование карт
  camera: ^0.10.5+2
  image: ^4.0.17
  
  # Безопасность
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  
  # Локализация
  intl: ^0.18.1
  
  # Уведомления
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500 