name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Validate gradle wrapper
      working-directory: ./android
      run: |
        chmod +x ./gradlew
        ./gradlew -v
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Create distribution directory
      run: mkdir -p apk-dist

    - name: Copy APK to distribution directory
      run: cp build/app/outputs/flutter-apk/app-release.apk apk-dist/roxcard-release.apk
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: apk-dist/roxcard-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 