name: Build APK

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Create necessary files
      run: flutter create --platforms=android --org com.roxcard .
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: roxcard-apk
        path: build/app/outputs/flutter-apk/app-release.apk
