name: Simple Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Create necessary files
      run: flutter create --platforms=android --org com.roxcard --project-name roxcard .
    
    - name: Build APK
      run: flutter build apk --release
      
    - name: List built APK
      run: ls -la build/app/outputs/flutter-apk/
      
    - name: Store APK
      run: mkdir -p $GITHUB_WORKSPACE/apk && cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/apk/
