name: Simple Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        cache: true
    
    - name: Create asset directories
      run: |
        mkdir -p assets/images
        mkdir -p assets/icons
        touch assets/images/.gitkeep
        touch assets/icons/.gitkeep
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Clean project
      run: flutter clean
    
    - name: Remove conflicting file
      run: rm -f android/app/src/main/java/com/example/roxcard/FlutterApplication.java
    
    - name: Build APK
      run: flutter build apk --debug
      
    - name: List built APK
      run: ls -la build/app/outputs/flutter-apk/
      
    - name: Store APK
      run: mkdir -p $GITHUB_WORKSPACE/apk && cp build/app/outputs/flutter-apk/app-debug.apk $GITHUB_WORKSPACE/apk/
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: $GITHUB_WORKSPACE/apk/app-debug.apk
